### ISSUE TITLE
Permission denied ERROR: 126 after build with Docker

### ISSUE THREAD

**Issue by scotchthy** [mecotrade/kidtracker#2]
Hi Developer,

After I built the image with "`docker-compose -f docker-builder.yml run --rm builder`" on my local Docker 
(And I also built on my cloud with "`docker-compose -f docker-builder.yml run --rm -e DOMAIN=my_domain_name.com -e IP=my_ip_address builder`". I got the same error) 

I'm stuck at this stage:
"/bin/sh: 1: build.sh: Permission denied
ERROR: 126"

I tried to add 
"`RUN chmod u+x build.sh`" 
after
"WORKDIR /build"
but it's not working. 

How can I pass this error?

![Screen Shot 2564-03-16 at 13 41 12](https://user-images.githubusercontent.com/48783145/111266615-5e78fd00-865d-11eb-98d3-4fe8347f4cc2.png)

**Comment by ofsahin** [comment]
i changed the dockerfile inside builder dir to this:
```
FROM maven:3.6.3-jdk-8
MAINTAINER Sergey Shadchin (sergei.shadchin@gmail.com)

RUN \
  apt-get update && \
  apt-get -y install nodejs npm

RUN mkdir -p /build
ADD build.sh /usr/local/bin/build.sh

RUN chmod u+x /usr/local/bin/build.sh

WORKDIR /build
CMD build.sh
```

added the line "RUN chmod u+x /usr/local/bin/build.sh", inspired by you

build passes the error you mentioned but i got a different error now.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.922 s
[INFO] Finished at: 2021-05-20T16:00:19Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project kidtracker: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: 1
```

**Comment by ofsahin** [comment]
ok, i managed to get passed the error by adding line:

`RUN npm install npm@latest -g`
after the part
```
RUN \
  apt-get update -y && \
  apt-get -y install nodejs npm
```
to update npm beyond debian busters version.
but then, i faced this error:
```
> kid-tracker@0.0.1 build:index
> browserify -p tinyify src/main/js/app.js > src/main/resources/static/js/index.js

sh: 1: cannot create src/main/resources/static/js/index.js: Directory nonexistent
ERROR: "build:index" exited with 2.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
i get passed this error by creating a js directory under /src/main/resources/static

final result:

```
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2021-05-20T16:30:45Z
[INFO] ------------------------------------------------------------------------
```
success !

**Comment by mecotrade** [comment]
Thank you, @ofsahin ! In new release [v2.0.0](../releases/tag/v2.0.0) I modified `Dockerfile` for builder and added placeholder for `src/main/resources/static/js` folder. 

Also I replaced Windows-like line ending to Unix-like ones. Now builder scritpt seems to work fine.
